--- Changed first line to reflect centos 7 env location --- Changed Version Number to 3.32 --- Removed Comments from Version 3.27 through Initial Release --- Added Variables for Zimbra and Lets Encrypt processing of certificate

diff --git a/ssl-cert-check b/ssl-cert-check
--- a/ssl-cert-check
+++ b/ssl-cert-check
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/env bash
 #
 # Program: SSL Certificate Check <ssl-cert-check>
 #
@@ -8,9 +8,12 @@
 #
 # Author: Matty < matty91 at gmail dot com >
 #
-# Current Version: 3.30
+# Current Version: 3.32
 #
 # Revision History:
+#
+# Version 3.32
+#  - Adding Lets Encrypt Certificate Renewal
 #
 # Version 3.31
 #  - Fixed the test for the -servername flag -- Kitson Consulting.
@@ -31,155 +34,8 @@
 # Version 3.28
 #  - Added a DEBUG option to assist with debugging folks who use the script
 #
-# Version 3.27
-#  - Allow white spaces to exist in the certificate file list
-#  - Add an additional check to pick up bad / non-existent certificates
-#  - Add a check to look for the existence of a mail program. Error out if it's not present.
-#  - Enable the TLS -servername extension by default - Juergen Knaack & Johan Denoyer
 #
-# Version 3.26
-#  - Allow the certificate type (PEM, DER, NET) to be passed on the command line
-#
-# Version 3.25
-#   - Check for "no route to host" errors -- Dan Doyle
-#   - Set RETCODE to 3 (unknown) if a connection error occurs -- Dan Doyle
-#   - Documentation fixes
-#
-# Version 3.24
-#   - Utilize the -clcerts option to limit the results to client certificates - Eitan Katznelson
-#
-# Version 3.23
-#   - Fixed typo in date2julian routine -- Ken Cook
-#
-# Version 3.22
-#   - Change the validation option to "-V"
-#   - Add a "-v" option to specify a specific protocol version (ssl2, ssl3 or tls)
-#
-# Version 3.21
-#   - Adjust e-mail checking to avoid exiting if notifications aren't enabled -- Nick Anderson
-#   - Added the number of days until expiration to the Nagios output -- Nick Anderson
-#
-# Version 3.20
-#   - Fixed a bug in certificate length checking -- Tim Nowaczyk
-#
-# Version 3.19
-#   - Added check to verify the certificate retrieved is valid
-#
-# Version 3.18
-#   - Add support for connecting to FTP servers -- Paul A Sand
-#
-# Version 3.17
-#   - Add support for connecting to imap servers -- Joerg Pareigis
-#
-# Version 3.16
-#   - Add support for connecting to the mail sbmission port -- Luis E. Munoz
-#
-# Version 3.15
-#   - Adjusted the file checking logic to use the correct certificate -- Maciej Szudejko
-#   - Add sbin to the default search paths for OpenBSD compatibility -- Alex Popov
-#   - Use cut instead of substring processing to ensure compatibility -- Alex Popov
-#
-# Version 3.14
-#   - Fixed the Common Name parser to handle DN's where the CN is not the last item
-#     eg. EmailAddr -- Jason Brothers
-#   - Added the ability to grab the serial number -- Jason Brothers
-#   - Added the "-b" option to print results without a header -- Jason Brothers
-#   - Added the "-v" option for certificate validation -- Jason Brothers
-#
-# Version 3.13
-#   - Updated the subject line to include the hostname as well as
-#     the common name embedded in the X509 certificate (if it's
-#     available) -- idea proposed by Mike Burns
-#
-#  Version 3.12
-#   - Updated the license to allow redistribution and modification
-#
-#  Version 3.11
-#   - Added ability to comment out lines in files passed
-#     to the "-f" option -- Brett Stauner
-#   - Fixed comment next to file processing logic
-#
-#  Version 3.10
-#   - Fixed POP3 port -- Simon Matter
-#
-#  Version 3.9
-#    - Switched binary location logic to use which utility
-#
-#  Version 3.8
-#    - Fixed display on 80 column displays
-#    - Cleaned up the formatting
-#
-#  Version 3.7
-#    - Fixed bug in NAGIOS tests -- Ben Allen
-#
-#  Version 3.6
-#    - Added support for certificates stored in PKCS#12 databases -- Ken Gallo
-#    - Cleaned up comments
-#    - Adjusted variables to be more consistent
-#
-#  Version 3.5
-#    - Added support for NAGIOS -- Quanah Gibson-Mount
-#    - Added additional checks for mail -- Quanah Gibson-Mount
-#    - Convert tabs to spaces -- Quanah Gibson-Mount
-#    - Cleaned up usage() routine
-#    - Added additional checks for openssl
-#
-#  Version 3.4
-#   - Added a missing "{" to line 364 -- Ken Gallo
-#   - Move mktemp to the start of the main body to avoid errors
-#   - Adjusted default binary paths to make sure the script just works
-#     w/ Solaris, BSD and Linux hosts
-#
-#  Version 3.3
-#   - Added common name from X.509 certificate file to E-mail body / header -- Doug Curtis
-#   - Fixed several documentation errors
-#   - Use mktemp to create temporary files
-#   - Convert printf, sed and awk to variables
-#   - Check for printf, sed, awk and mktemp binaries
-#   - Add additional logic to make sure mktemp returned a valid temporary file
-#
-#  Version 3.2
-#   - Added option to list certificates in the file passed to "-f".
-#
-#  Version 3.1
-#   - Added handling for starttls for smtp -- Marco Amrein
-#   - Added handling for starttls for pop3 (without s) -- Marco Amrein
-#   - Removed extra spacing at end of script
-#
-#  Version 3.0
-#   - Added "-i" option to print certificate issuer
-#   - Removed $0 from Subject line of outbound e-mails
-#   - Fixed some typographical errors
-#   - Removed redundant "-b" option
-#
-#  Version 2.0
-#    - Fixed an issue with e-mails formatting incorrectly
-#    - Added additional space to host column -- Darren-Perot Spruell
-#    - Replaced GNU date dependency with CHRIS F. A. JOHNSON's
-#      date2julian shell function. This routine can be found on
-#      page 170 of Chris's book "Shell Scripting Recipes: A
-#      Problem-Solution Approach," ISBN #1590594711. Julian function
-#      was created based on a post to comp.unix.shell by Tapani Tarvainen.
-#    - Cleaned up function descriptions
-#    - Removed several lines of redundant code
-#    - Adjusted the help message
-#
-#   Version 1.1
-#    - Added "-c" flag to report expiration status of a PEM encoded
-#      certificate -- Hampus Lundqvist
-#    - Updated the prints messages to display the reason a connection
-#      failed (connection refused, connection timeout, bad cert, etc)
-#    - Updated the GNU date checking routines
-#    - Added checks for each binary required
-#    - Added checks for connection timeouts
-#    - Added checks for GNU date
-#    - Added a "-h" option
-#    - Cleaned up the documentation
-#
-#  Version 1.0
-#      Initial Release
-#
-# Last Updated: 12-12-2016
+# Last Updated: 05-31-2018
 #
 # Purpose:
 #  ssl-cert-check checks to see if a digital certificate in X.509 format
@@ -231,7 +87,7 @@ ADMIN="support@niesc.k12.in.us"
 SENDER="nebsawebserver@nebsa.org"
 
 # Number of days in the warning threshhold (cmdline: -x)
-WARNDAYS=15
+WARNDAYS=70
 
 # If QUIET is set to TRUE, don't print anything on the console (cmdline: -q)
 QUIET="FALSE"
@@ -254,8 +110,14 @@ CERTTYPE="pem"
 # Protocol version to use (cmdline: -v)
 VERSION=""
 
-# AutoRenewal LetsEncrypt Certificate
-AUTORENEWAL="TRUE"
+# Renewal LetsEncrypt Certificate
+LETSENCRYPTRENEWAL="TRUE"
+
+# How Many Days till Expire to try to renew Letsencrypt Certificate
+LETSENCRYPTDAYSTORENEW=15
+
+# Running on a Zimbra Mail Server
+ZIMBRAMAIL="FALSE"
 
 # Enable debugging
 DEBUG=0
@@ -269,6 +131,7 @@ PRINTF=$(which printf)
 SED=$(which sed)
 MKTEMP=$(which mktemp)
 FIND=$(which find)
+CERTBOT=$(which certbot)
 
 # Try to find a mail client
 if [ -f /usr/bin/mailx ]
@@ -314,7 +177,6 @@ SUMMARY_MIN_PORT=
 
 # Set the default umask to be somewhat restrictive
 umask 077
-
 
 #####################################################
 ### Send email
@@ -475,22 +337,22 @@ print_heading()
         if [ "${QUIET}" != "TRUE" ] && [ "${ISSUER}" = "TRUE" ] && [ "${NAGIOS}" != "TRUE" ] && [ "${VALIDATION}" != "TRUE" ]
         then
             ${PRINTF} "\n%-35s %-17s %-8s %-11s %-4s\n" "Host" "Issuer" "Status" "Expires" "Days"
-            echo "----------------------------------- ----------------- -------- ----------- ----"
+            echo "------------------------------------------------------- ----------------- -------- ----------- ----"
 
         elif [ "${QUIET}" != "TRUE" ] && [ "${ISSUER}" = "TRUE" ] && [ "${NAGIOS}" != "TRUE" ] && [ "${VALIDATION}" == "TRUE" ]
         then
             ${PRINTF} "\n%-35s %-35s %-32s %-17s\n" "Host" "Common Name" "Serial #" "Issuer"
-            echo "----------------------------------- ----------------------------------- -------------------------------- -----------------"
+            echo "--------------------------------------------- ----------------------------------- -------------------------------- -----------------"
 
         elif [ "${QUIET}" != "TRUE" ] && [ "${NAGIOS}" != "TRUE" ] && [ "${VALIDATION}" != "TRUE" ]
         then
-            ${PRINTF} "\n%-47s %-12s %-12s %-4s\n" "Host" "Status" "Expires" "Days"
-            echo "----------------------------------------------- ------------ ------------ ----"
+            ${PRINTF} "\n%-58s %-12s %-12s %-4s\n" "Host"                   "Status" "Expires" "Days"
+            echo "--------------------------------------------------------- ------------ ------------ ----"
 
         elif [ "${QUIET}" != "TRUE" ] && [ "${NAGIOS}" != "TRUE" ] && [ "${VALIDATION}" == "TRUE" ]
         then
             ${PRINTF} "\n%-35s %-35s %-32s\n" "Host" "Common Name" "Serial #"
-            echo "----------------------------------- ----------------------------------- --------------------------------"
+            echo "--------------------------------------------- ----------------------------------- --------------------------------"
         fi
     fi
 }
@@ -768,13 +630,29 @@ check_file_status() {
     then
         if [ "${ALARM}" = "TRUE" ]
         then
-            send_mail ${SENDER} ${ADMIN} "Certificate for ${HOST} \"(CN: ${COMMONNAME})\" will expire in ${WARNDAYS}-days or less" \
-                "The SSL certificate for ${HOST} \"(CN: ${COMMONNAME})\" will expire on ${CERTDATE}"
-	    if [ "${AUTORENEWAL}" = "TRUE" ]
+            ## send_mail ${SENDER} ${ADMIN} "Certificate for ${HOST} \"(CN: ${COMMONNAME})\" will expire in ${WARNDAYS}-days or less" \
+            ##    "The SSL certificate for ${HOST} \"(CN: ${COMMONNAME})\" will expire on ${CERTDATE}"
+            if [ "${LETSENCRYPTRENEWAL}" = "TRUE" ] && [ "${ZIMBRAMAIL}" = "FALSE" ]
             then
-		/usr/bin/certbot renew
-		systemctl restart nginx
-	    fi
+                if [ ${CERTDIFF} -lt ${LETSENCRYPTDAYSTORENEW} ]
+                then
+                    echo ${CERTBOT} renew "ZimbraMail = FALSE"
+                    # systemctl restart nginx
+                else
+                    echo "Zimbra Mail IS False"
+                    echo "Certificate days left is not lower ${LETSENCRYPTDAYSTORENEW}"
+                fi
+            elif [ "${LETSENCRYPTRENEWAL}" = "TRUE" ] && [ "${ZIMBRAMAIL}" = "TRUE" ]
+            then
+                if [ ${CERTDIFF} -lt ${LETSENCRYPTDAYSTORENEW} ]
+                then
+                    echo ${CERTBOT} renew "ZimbraMail = True"
+                    # systemctl restart nginx
+                else
+                    echo "Zimbra Mail is True"
+                    echo "Certificate days left is not lower ${LETSENCRYPTDAYSTORENEW}"
+                fi
+            fi
         fi
         prints ${HOST} ${PORT} "Expiring" "${CERTDATE}" "${CERTDIFF}" "${CERTISSUER}" "${COMMONNAME}" "${SERIAL}"
         RETCODE_LOCAL=1
@@ -835,6 +713,13 @@ if [ ! -f ${DATE} ]
 then
     echo "ERROR: The date binary does not exist in ${DATE} ."
     echo "FIX: Please modify the \${DATE} variable in the program header."
+    exit 1
+fi
+
+if [ ! -f ${CERTBOT} ]
+then
+    echo "ERROR: The certbot binary does not exist in ${CERTBOT} ."
+    echo "FIX: Please modify the \${CERTBOT} variable in the program header."
     exit 1
 fi
 
